spring.application.name=maintenance-service
server.port=${PORT}

#db
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

#security
spring.security.userResponse.name=rahim.mustafo.x
spring.security.userResponse.password=18122009

#swagger
springdoc.swagger-ui=true

