spring.application.name=maintenance-service-user-service
server.port=${PORT}

#db
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

#swagger enabled
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

